library(tidyverse)
data("mpg")
ggplot()
ggplot("mpg")
ggplot(mpg)
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy))
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy,color=class))
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy),color="blue")
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy))+facet_wrap(~class,nrow=3)
ggplot(data=mpg)+geom_point(mapping=aes(x=displ,y=hwy))+facet_grid(drv~cyl)
ggplot(data=mpg)+geom_smooth(mapping=aes(x=displ,y=hwy,linetype=drv))
log(mpg$displ)
data<-data.frame(displ=c(scale(mpg$displ,center=FALSE)),cty=c(scale(mpg$cty,center=FALSE)),hwy=c(scale(mpg$hwy,center=FALSE)))
scale(data)

