library(tm)
df<-data.frame(yelp$business_categories,yelp$business_name,yelp$text)
coffee<-grep("coffee",yelp$business_categories,value=TRUE,ignore.case=TRUE)
doc<-VCorpus(VectorSource(coffee))
doc<-tm_map(doc,content_transformer(tolower))
doc<-tm_map(doc,removeNumbers)
doc<-tm_map(doc,removeWords,stopwords("english"))
doc<-tm_map(doc,stripWhitespace)
stemmed.doc<-tm_map(doc,stemDocument)
dtm<-TermDocumentMatrix(stemmed.doc)
m<-as.matrix(dtm)
v<-sort(rowSums(m),decreasing=TRUE)
d<-data.frame(word=names(v),frequency=v)
View(d)
library(wordcloud)
library(RColorBrewer)
wordcloud(words=d$word,freq=d$freq,min.freq=1,max.words=20)

